spring.application.name=spring-cloud-config-server
server.port=8888

#spring.cloud.config.server.git.uri=file:\\C:/Users/PELUMI/Desktop/Spring-boot-Microservices-project/git-localconfig-repo
spring.cloud.config.server.git.cloneOnStart=true

spring.cloud.config.server.git.uri=file:///Users/seojeongchang/VSProject/Spring-boot-Banking-API/git-localconfig-repo

spring.cloud.config.server.git.default-label=main
server.tomcat.max-threads = 1


management.endpoints.metrics.enabled=true
management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include= *
management.endpoint.health.show-details=always